### ISSUE TITLE
在sku属性不交叉的情况下如何点击进行切换

### ISSUE THREAD

**Issue by jerry9433** [wuhenzhizao/android-sku#14]
eg:颜色：红褐色  重量:25g
     颜色：黄色      重量:1kg

当选中第一个Sku时，无法点击选中第二个Sku,需要先把当前选中去掉才能点击，如何做到点击就切换呢

**Comment by wuhenzhizao** [comment]
你提供了两组SKU，在UI上是两行，分别为：
颜色：  红褐色   黄色
重量：  25g         1kg
SKU是一个组合，同时只能选择一种组合，我不知道有没有get到你的点

**Comment by jerry9433** [comment]
例如现在默认选中红褐色+25g，这时黄色+1kg是置灰不可点击的，如何设置点击黄色或1kg其一后选中黄色+1kg，置灰红褐色+25g，Get了吗

**Comment by jerry9433** [comment]
？？？

**Comment by wuhenzhizao** [comment]
需要先取消选中的那一组
