### ISSUE TITLE
sellingPrice是long，在实际开发中sellingPrice是double的。无法转换。

### ISSUE THREAD

**Issue by lexluthors** [wuhenzhizao/android-sku#15]
sellingPrice是long，在实际开发中sellingPrice是double的。无法转换。这么脑残的设计，不知道怎么想的

**Comment by wuhenzhizao** [comment]
一般不用double，在传输过程中，以分为单位比较多。无果无法修改，将double转换成long也是可以的

**Comment by lexluthors** [comment]
@wuhenzhizao 请问0.05转成long怎么转？
