### ISSUE TITLE
没有库存的按钮应该可以点击，因为库存的有无是相对的

### ISSUE THREAD

**Issue by CK875430315** [wuhenzhizao/android-sku#5]
可以看下京东的

**Comment by wuhenzhizao** [comment]
相对这个词有点不妥，只能说库存是动态的。京东没有做限制，是在选中的时候动态获取。
我可以加一个设置选项，设置库存为0，是否可选中

**Comment by CK875430315** [comment]
恩，在不可点击的情况下让他可以点击被选中，然后拿着它去跟解析出来的sku实体做查找，来决定那些和它比较的sku是不是可以点击的，这个可以实现么，被这个困扰很久了

**Comment by CK875430315** [comment]
我的项目里是一个四维的：渠道，网络，颜色，内存

**Comment by wuhenzhizao** [comment]
你指的不可点击指的是可以点击，只不过是灰色吧

**Comment by CK875430315** [comment]
能加下你的qq请教下么，这样沟通有点费劲

**Comment by CK875430315** [comment]
我的875430315

**Comment by wuhenzhizao** [comment]
你看一下README下面，有个群，加一下

**Comment by CK875430315** [comment]
加了
