### ISSUE TITLE
demo弹出的dialog在部分机型上距离底部有缝隙

### ISSUE THREAD

**Issue by protectedMan** [wuhenzhizao/android-sku#6]
如图
![image](https://user-images.githubusercontent.com/17565737/36879269-e4af9dc8-1dfd-11e8-8bde-bbd6c546bd6f.png)

**Comment by wuhenzhizao** [comment]
请提供手机信息：手机型号，系统型号，还有用真机，这个手机是否使用了隐藏式导航栏

**Comment by protectedMan** [comment]
发生问题的机子确实是用的隐藏式导航栏

**Comment by wuhenzhizao** [comment]
把信息提供完整，不然没法定位

**Comment by protectedMan** [comment]
三星galaxy note edge ,android 6.0.1
魅蓝note2 ,android 5.1

**Comment by wuhenzhizao** [comment]
谢谢，我周末修复一下，之前没碰到过，这个应该是dialog与导航栏的兼容问题

**Comment by wuhenzhizao** [comment]
@protectedMan ，图片里面的模拟器是什么型号呀，你提供的那几款我找不到只能用模拟器

**Comment by protectedMan** [comment]
没有模拟器，那个图片只是带壳截图。 不过这个问题我已经修复了，我可以pull request给你看看。

**Comment by wuhenzhizao** [comment]
可以提交一个request
