### ISSUE TITLE
当只有一组的时候，列表显示为空（bug， bug， bug）

### ISSUE THREAD

**Issue by jack-laowang** [wuhenzhizao/android-sku#8]
比如sku只有一种的时候，列表是空的，
颜色:均色

**Comment by wuhenzhizao** [comment]
验证没有问题，可以修改string.xml中的product测试数据为
<string name="product">{\"id\":\"101\",\"name\":\"羊毛呢2017秋冬装新款女装韩版棉服宽松棉袄处理短款棉衣外套反季\",\"status\":\"1\",\"mainImage\":\"https://img.alicdn.com/bao/uploaded/i3/1754317604/TB1H1DViesAV1JjSZFsXXadZXXa_!!0-item_pic.jpg_b.jpg\",\"sellingPrice\":26800,\"originPrice\":36800,\"currencyUnit\":\"¥\",\"measurementUnit\":\"件\",\"saleQuantity\":1335,\"stockQuantity\":10998,\"medias\":[\"https://img.alicdn.com/imgextra/i3/1754317604/TB2UkuShvBNTKJjy1zdXXaScpXa_!!1754317604.jpg\",\"https://img.alicdn.com/imgextra/i4/1754317604/TB2JNyYhvBNTKJjSszeXXcu2VXa_!!1754317604.jpg\",\"https://img.alicdn.com/imgextra/i4/1754317604/TB2ZFJxiaagSKJjy0FhXXcrbFXa_!!1754317604.jpg\",\"https://img.alicdn.com/imgextra/i3/1754317604/TB2.ohtijihSKJjy0FfXXbGzFXa_!!1754317604.jpg\"],\"skus\":[{\"id\":\"1\",\"itemId\":\"101\",\"mainImage\":\"https://img.alicdn.com/imgextra/i3/1754317604/TB2UkuShvBNTKJjy1zdXXaScpXa_!!1754317604.jpg\",\"originPrice\":36800,\"sellingPrice\":26800,\"stockQuantity\":21,\"attributes\":[{\"key\":\"颜色\",\"value\":\"粉色\"}]}]}</string>
