### ISSUE TITLE
如果只有一组 不会显示出来，bug

### ISSUE THREAD

**Issue by jack-laowang** [wuhenzhizao/android-sku#9]
例如：颜色 红色
只有一组的话 什么都没有，显示不出来

**Comment by wuhenzhizao** [comment]
上次的issue跟你说了，可以用那组数据测试，没问题的，我不晓得是不是你的数据结构不匹配 #8

**Comment by jack-laowang** [comment]
对 是我这边的问题，这个bug关闭了吧 thanks
